%/****************************************************************************/
%/****************************************************************************/
%/* (C) Copyright 2016 SIGRA Teechnologies GmbH                              */
%/* File Name: tapas_types.m                                                  */
%/* Author: TAPAS Generated                                                   */
%/* Status: Draft Version                                                    */
%/****************************************************************************/
%/****************************************************************************/

function aDbcEnumAvailable = tapas_types_dbc()


aDbcEnumAvailable = {};


Simulink.defineIntEnumType('CIPVFlag_t', ... 
{'CIPV','not'}, ... 
[1;0],...
'Description', 'enum for signal CIPVFlag', ...
'DefaultValue', 'CIPV', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'CIPVFlag_t'];


Simulink.defineIntEnumType('Cut_in_and_Out_t', ... 
{'cut_out','cut_in','out_host_lane','in_host_lane','undefined'}, ... 
[4;3;2;1;0],...
'Description', 'enum for signal Cut_in_and_Out', ...
'DefaultValue', 'cut_out', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'Cut_in_and_Out_t'];


Simulink.defineIntEnumType('BlinkerInfo_t', ... 
{'both','right','left','off','unavailable'}, ... 
[4;3;2;1;0],...
'Description', 'enum for signal BlinkerInfo', ...
'DefaultValue', 'both', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'BlinkerInfo_t'];


Simulink.defineIntEnumType('ObstacleType_t', ... 
{'Bicycle','pedestrian','bike','truck','vehicle'}, ... 
[4;3;2;1;0],...
'Description', 'enum for signal ObstacleType', ...
'DefaultValue', 'Bicycle', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'ObstacleType_t'];


Simulink.defineIntEnumType('ViewRangeAvailability_t', ... 
{'valid','not'}, ... 
[1;0],...
'Description', 'enum for signal ViewRangeAvailability', ...
'DefaultValue', 'valid', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'ViewRangeAvailability_t'];


Simulink.defineIntEnumType('ViewRangeAvailability_t', ... 
{'valid','not'}, ... 
[1;0],...
'Description', 'enum for signal ViewRangeAvailability', ...
'DefaultValue', 'valid', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'ViewRangeAvailability_t'];


Simulink.defineIntEnumType('LaneType2_t', ... 
{'undecided','undecided','undecided','undecided','undecided','solid','undecided'}, ... 
[6;5;4;3;2;1;0],...
'Description', 'enum for signal LaneType2', ...
'DefaultValue', 'undecided', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'LaneType2_t'];


Simulink.defineIntEnumType('ViewRangeAvailability_t', ... 
{'valid','not'}, ... 
[1;0],...
'Description', 'enum for signal ViewRangeAvailability', ...
'DefaultValue', 'valid', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'ViewRangeAvailability_t'];


Simulink.defineIntEnumType('LaneType2_t', ... 
{'undecided','undecided','undecided','undecided','undecided','solid','undecided'}, ... 
[6;5;4;3;2;1;0],...
'Description', 'enum for signal LaneType2', ...
'DefaultValue', 'undecided', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'LaneType2_t'];


Simulink.defineIntEnumType('ViewRangeAvailability_t', ... 
{'valid','not'}, ... 
[1;0],...
'Description', 'enum for signal ViewRangeAvailability', ...
'DefaultValue', 'valid', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'ViewRangeAvailability_t'];


Simulink.defineIntEnumType('LaneType2_t', ... 
{'undecided','undecided','undecided','undecided','undecided','solid','undecided'}, ... 
[6;5;4;3;2;1;0],...
'Description', 'enum for signal LaneType2', ...
'DefaultValue', 'undecided', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'LaneType2_t'];


Simulink.defineIntEnumType('ViewRangeAvailability_t', ... 
{'valid','not'}, ... 
[1;0],...
'Description', 'enum for signal ViewRangeAvailability', ...
'DefaultValue', 'valid', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'ViewRangeAvailability_t'];


Simulink.defineIntEnumType('LaneType2_t', ... 
{'undecided','undecided','undecided','undecided','undecided','solid','undecided'}, ... 
[6;5;4;3;2;1;0],...
'Description', 'enum for signal LaneType2', ...
'DefaultValue', 'undecided', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'LaneType2_t'];


Simulink.defineIntEnumType('ViewRangeAvailability_t', ... 
{'valid','not'}, ... 
[1;0],...
'Description', 'enum for signal ViewRangeAvailability', ...
'DefaultValue', 'valid', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'ViewRangeAvailability_t'];


Simulink.defineIntEnumType('LaneType2_t', ... 
{'undecided','undecided','undecided','undecided','undecided','solid','undecided'}, ... 
[6;5;4;3;2;1;0],...
'Description', 'enum for signal LaneType2', ...
'DefaultValue', 'undecided', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'LaneType2_t'];


Simulink.defineIntEnumType('ViewRangeAvailability_t', ... 
{'valid','not'}, ... 
[1;0],...
'Description', 'enum for signal ViewRangeAvailability', ...
'DefaultValue', 'valid', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'ViewRangeAvailability_t'];


Simulink.defineIntEnumType('LaneType2_t', ... 
{'undecided','undecided','undecided','undecided','undecided','solid','undecided'}, ... 
[6;5;4;3;2;1;0],...
'Description', 'enum for signal LaneType2', ...
'DefaultValue', 'undecided', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'LaneType2_t'];


Simulink.defineIntEnumType('ViewRangeAvailability_t', ... 
{'valid','not'}, ... 
[1;0],...
'Description', 'enum for signal ViewRangeAvailability', ...
'DefaultValue', 'valid', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'ViewRangeAvailability_t'];


Simulink.defineIntEnumType('LaneType2_t', ... 
{'undecided','undecided','undecided','undecided','undecided','solid','undecided'}, ... 
[6;5;4;3;2;1;0],...
'Description', 'enum for signal LaneType2', ...
'DefaultValue', 'undecided', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'LaneType2_t'];


Simulink.defineIntEnumType('ViewRangeAvailability_t', ... 
{'valid','not'}, ... 
[1;0],...
'Description', 'enum for signal ViewRangeAvailability', ...
'DefaultValue', 'valid', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'ViewRangeAvailability_t'];


Simulink.defineIntEnumType('LaneType2_t', ... 
{'undecided','undecided','undecided','undecided','undecided','solid','undecided'}, ... 
[6;5;4;3;2;1;0],...
'Description', 'enum for signal LaneType2', ...
'DefaultValue', 'undecided', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'LaneType2_t'];


Simulink.defineIntEnumType('RefPoint2Validity_t', ... 
{'valid','not'}, ... 
[1;0],...
'Description', 'enum for signal RefPoint2Validity', ...
'DefaultValue', 'valid', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'RefPoint2Validity_t'];


Simulink.defineIntEnumType('RefPoint1Validity_t', ... 
{'valid','not'}, ... 
[1;0],...
'Description', 'enum for signal RefPoint1Validity', ...
'DefaultValue', 'valid', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'RefPoint1Validity_t'];


Simulink.defineIntEnumType('ViewRangeAvailability_t', ... 
{'valid','not'}, ... 
[1;0],...
'Description', 'enum for signal ViewRangeAvailability', ...
'DefaultValue', 'valid', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'ViewRangeAvailability_t'];


Simulink.defineIntEnumType('ViewRangeAvailability_t', ... 
{'valid','not'}, ... 
[1;0],...
'Description', 'enum for signal ViewRangeAvailability', ...
'DefaultValue', 'valid', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'ViewRangeAvailability_t'];


Simulink.defineIntEnumType('CIPVFlag_t', ... 
{'CIPV','not'}, ... 
[1;0],...
'Description', 'enum for signal CIPVFlag', ...
'DefaultValue', 'CIPV', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'CIPVFlag_t'];


Simulink.defineIntEnumType('Cut_in_and_Out_A14_t', ... 
{'cut_out','cut_in','out_host_lane','in_host_lane','undefined'}, ... 
[4;3;2;1;0],...
'Description', 'enum for signal Cut_in_and_Out_A14', ...
'DefaultValue', 'cut_out', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'Cut_in_and_Out_A14_t'];


Simulink.defineIntEnumType('BlinkerInfo_A14_t', ... 
{'both','right','left','off','unavailable'}, ... 
[4;3;2;1;0],...
'Description', 'enum for signal BlinkerInfo_A14', ...
'DefaultValue', 'both', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'BlinkerInfo_A14_t'];


Simulink.defineIntEnumType('ObstacleType_A14_t', ... 
{'Bicycle','pedestrian','bike','truck','vehicle'}, ... 
[4;3;2;1;0],...
'Description', 'enum for signal ObstacleType_A14', ...
'DefaultValue', 'Bicycle', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'ObstacleType_A14_t'];


Simulink.defineIntEnumType('CIPVFlag_t', ... 
{'CIPV','not'}, ... 
[1;0],...
'Description', 'enum for signal CIPVFlag', ...
'DefaultValue', 'CIPV', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'CIPVFlag_t'];


Simulink.defineIntEnumType('Cut_in_and_Out_A13_t', ... 
{'cut_out','cut_in','out_host_lane','in_host_lane','undefined'}, ... 
[4;3;2;1;0],...
'Description', 'enum for signal Cut_in_and_Out_A13', ...
'DefaultValue', 'cut_out', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'Cut_in_and_Out_A13_t'];


Simulink.defineIntEnumType('BlinkerInfo_A13_t', ... 
{'both','right','left','off','unavailable'}, ... 
[4;3;2;1;0],...
'Description', 'enum for signal BlinkerInfo_A13', ...
'DefaultValue', 'both', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'BlinkerInfo_A13_t'];


Simulink.defineIntEnumType('ObstacleType_A13_t', ... 
{'Bicycle','pedestrian','bike','truck','vehicle'}, ... 
[4;3;2;1;0],...
'Description', 'enum for signal ObstacleType_A13', ...
'DefaultValue', 'Bicycle', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'ObstacleType_A13_t'];


Simulink.defineIntEnumType('CIPVFlag_t', ... 
{'CIPV','not'}, ... 
[1;0],...
'Description', 'enum for signal CIPVFlag', ...
'DefaultValue', 'CIPV', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'CIPVFlag_t'];


Simulink.defineIntEnumType('Cut_in_and_Out_A12_t', ... 
{'cut_out','cut_in','out_host_lane','in_host_lane','undefined'}, ... 
[4;3;2;1;0],...
'Description', 'enum for signal Cut_in_and_Out_A12', ...
'DefaultValue', 'cut_out', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'Cut_in_and_Out_A12_t'];


Simulink.defineIntEnumType('BlinkerInfo_A12_t', ... 
{'both','right','left','off','unavailable'}, ... 
[4;3;2;1;0],...
'Description', 'enum for signal BlinkerInfo_A12', ...
'DefaultValue', 'both', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'BlinkerInfo_A12_t'];


Simulink.defineIntEnumType('ObstacleType_A12_t', ... 
{'Bicycle','pedestrian','bike','truck','vehicle'}, ... 
[4;3;2;1;0],...
'Description', 'enum for signal ObstacleType_A12', ...
'DefaultValue', 'Bicycle', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'ObstacleType_A12_t'];


Simulink.defineIntEnumType('CIPVFlag_t', ... 
{'CIPV','not'}, ... 
[1;0],...
'Description', 'enum for signal CIPVFlag', ...
'DefaultValue', 'CIPV', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'CIPVFlag_t'];


Simulink.defineIntEnumType('Cut_in_and_Out_A11_t', ... 
{'cut_out','cut_in','out_host_lane','in_host_lane','undefined'}, ... 
[4;3;2;1;0],...
'Description', 'enum for signal Cut_in_and_Out_A11', ...
'DefaultValue', 'cut_out', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'Cut_in_and_Out_A11_t'];


Simulink.defineIntEnumType('BlinkerInfo_A11_t', ... 
{'both','right','left','off','unavailable'}, ... 
[4;3;2;1;0],...
'Description', 'enum for signal BlinkerInfo_A11', ...
'DefaultValue', 'both', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'BlinkerInfo_A11_t'];


Simulink.defineIntEnumType('ObstacleType_A11_t', ... 
{'Bicycle','pedestrian','bike','truck','vehicle'}, ... 
[4;3;2;1;0],...
'Description', 'enum for signal ObstacleType_A11', ...
'DefaultValue', 'Bicycle', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'ObstacleType_A11_t'];


Simulink.defineIntEnumType('CIPVFlag_t', ... 
{'CIPV','not'}, ... 
[1;0],...
'Description', 'enum for signal CIPVFlag', ...
'DefaultValue', 'CIPV', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'CIPVFlag_t'];


Simulink.defineIntEnumType('Cut_in_and_Out_A10_t', ... 
{'cut_out','cut_in','out_host_lane','in_host_lane','undefined'}, ... 
[4;3;2;1;0],...
'Description', 'enum for signal Cut_in_and_Out_A10', ...
'DefaultValue', 'cut_out', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'Cut_in_and_Out_A10_t'];


Simulink.defineIntEnumType('BlinkerInfo_A10_t', ... 
{'both','right','left','off','unavailable'}, ... 
[4;3;2;1;0],...
'Description', 'enum for signal BlinkerInfo_A10', ...
'DefaultValue', 'both', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'BlinkerInfo_A10_t'];


Simulink.defineIntEnumType('ObstacleType_A10_t', ... 
{'Bicycle','pedestrian','bike','truck','vehicle'}, ... 
[4;3;2;1;0],...
'Description', 'enum for signal ObstacleType_A10', ...
'DefaultValue', 'Bicycle', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'ObstacleType_A10_t'];


Simulink.defineIntEnumType('ST_OBJ_DIST_HLB_t', ... 
{'invalid','oncoming','preceding','no'}, ... 
[3;2;vehicle;1],...
'Description', 'enum for signal ST_OBJ_DIST_HLB', ...
'DefaultValue', 'invalid', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'ST_OBJ_DIST_HLB_t'];


Simulink.defineIntEnumType('CIPVFlag_t', ... 
{'CIPV','not'}, ... 
[1;0],...
'Description', 'enum for signal CIPVFlag', ...
'DefaultValue', 'CIPV', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'CIPVFlag_t'];


Simulink.defineIntEnumType('CIPVFlag_t', ... 
{'CIPV','not'}, ... 
[1;0],...
'Description', 'enum for signal CIPVFlag', ...
'DefaultValue', 'CIPV', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'CIPVFlag_t'];


Simulink.defineIntEnumType('CIPVFlag_t', ... 
{'CIPV','not'}, ... 
[1;0],...
'Description', 'enum for signal CIPVFlag', ...
'DefaultValue', 'CIPV', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'CIPVFlag_t'];


Simulink.defineIntEnumType('CIPVFlag_t', ... 
{'CIPV','not'}, ... 
[1;0],...
'Description', 'enum for signal CIPVFlag', ...
'DefaultValue', 'CIPV', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'CIPVFlag_t'];


Simulink.defineIntEnumType('CIPVFlag_t', ... 
{'CIPV','not'}, ... 
[1;0],...
'Description', 'enum for signal CIPVFlag', ...
'DefaultValue', 'CIPV', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'CIPVFlag_t'];


Simulink.defineIntEnumType('CIPVFlag_t', ... 
{'CIPV','not'}, ... 
[1;0],...
'Description', 'enum for signal CIPVFlag', ...
'DefaultValue', 'CIPV', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'CIPVFlag_t'];


Simulink.defineIntEnumType('CIPVFlag_t', ... 
{'CIPV','not'}, ... 
[1;0],...
'Description', 'enum for signal CIPVFlag', ...
'DefaultValue', 'CIPV', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'CIPVFlag_t'];


Simulink.defineIntEnumType('Cut_in_and_Out_A9_t', ... 
{'cut_out','cut_in','out_host_lane','in_host_lane','undefined'}, ... 
[4;3;2;1;0],...
'Description', 'enum for signal Cut_in_and_Out_A9', ...
'DefaultValue', 'cut_out', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'Cut_in_and_Out_A9_t'];


Simulink.defineIntEnumType('BlinkerInfo_A9_t', ... 
{'both','right','left','off','unavailable'}, ... 
[4;3;2;1;0],...
'Description', 'enum for signal BlinkerInfo_A9', ...
'DefaultValue', 'both', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'BlinkerInfo_A9_t'];


Simulink.defineIntEnumType('ObstacleType_A9_t', ... 
{'Bicycle','pedestrian','bike','truck','vehicle'}, ... 
[4;3;2;1;0],...
'Description', 'enum for signal ObstacleType_A9', ...
'DefaultValue', 'Bicycle', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'ObstacleType_A9_t'];


Simulink.defineIntEnumType('Cut_in_and_Out_A8_t', ... 
{'cut_out','cut_in','out_host_lane','in_host_lane','undefined'}, ... 
[4;3;2;1;0],...
'Description', 'enum for signal Cut_in_and_Out_A8', ...
'DefaultValue', 'cut_out', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'Cut_in_and_Out_A8_t'];


Simulink.defineIntEnumType('BlinkerInfo_A8_t', ... 
{'both','right','left','off','unavailable'}, ... 
[4;3;2;1;0],...
'Description', 'enum for signal BlinkerInfo_A8', ...
'DefaultValue', 'both', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'BlinkerInfo_A8_t'];


Simulink.defineIntEnumType('ObstacleType_A8_t', ... 
{'Bicycle','pedestrian','bike','truck','vehicle'}, ... 
[4;3;2;1;0],...
'Description', 'enum for signal ObstacleType_A8', ...
'DefaultValue', 'Bicycle', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'ObstacleType_A8_t'];


Simulink.defineIntEnumType('Cut_in_and_Out_A7_t', ... 
{'cut_out','cut_in','out_host_lane','in_host_lane','undefined'}, ... 
[4;3;2;1;0],...
'Description', 'enum for signal Cut_in_and_Out_A7', ...
'DefaultValue', 'cut_out', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'Cut_in_and_Out_A7_t'];


Simulink.defineIntEnumType('BlinkerInfo_A7_t', ... 
{'both','right','left','off','unavailable'}, ... 
[4;3;2;1;0],...
'Description', 'enum for signal BlinkerInfo_A7', ...
'DefaultValue', 'both', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'BlinkerInfo_A7_t'];


Simulink.defineIntEnumType('ObstacleType_A7_t', ... 
{'Bicycle','pedestrian','bike','truck','vehicle'}, ... 
[4;3;2;1;0],...
'Description', 'enum for signal ObstacleType_A7', ...
'DefaultValue', 'Bicycle', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'ObstacleType_A7_t'];


Simulink.defineIntEnumType('Cut_in_and_Out_A6_t', ... 
{'cut_out','cut_in','out_host_lane','in_host_lane','undefined'}, ... 
[4;3;2;1;0],...
'Description', 'enum for signal Cut_in_and_Out_A6', ...
'DefaultValue', 'cut_out', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'Cut_in_and_Out_A6_t'];


Simulink.defineIntEnumType('BlinkerInfo_A6_t', ... 
{'both','right','left','off','unavailable'}, ... 
[4;3;2;1;0],...
'Description', 'enum for signal BlinkerInfo_A6', ...
'DefaultValue', 'both', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'BlinkerInfo_A6_t'];


Simulink.defineIntEnumType('ObstacleType_A6_t', ... 
{'Bicycle','pedestrian','bike','truck','vehicle'}, ... 
[4;3;2;1;0],...
'Description', 'enum for signal ObstacleType_A6', ...
'DefaultValue', 'Bicycle', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'ObstacleType_A6_t'];


Simulink.defineIntEnumType('Cut_in_and_Out_A5_t', ... 
{'cut_out','cut_in','out_host_lane','in_host_lane','undefined'}, ... 
[4;3;2;1;0],...
'Description', 'enum for signal Cut_in_and_Out_A5', ...
'DefaultValue', 'cut_out', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'Cut_in_and_Out_A5_t'];


Simulink.defineIntEnumType('BlinkerInfo_A5_t', ... 
{'both','right','left','off','unavailable'}, ... 
[4;3;2;1;0],...
'Description', 'enum for signal BlinkerInfo_A5', ...
'DefaultValue', 'both', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'BlinkerInfo_A5_t'];


Simulink.defineIntEnumType('ObstacleType_A5_t', ... 
{'Bicycle','pedestrian','bike','truck','vehicle'}, ... 
[4;3;2;1;0],...
'Description', 'enum for signal ObstacleType_A5', ...
'DefaultValue', 'Bicycle', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'ObstacleType_A5_t'];


Simulink.defineIntEnumType('Cut_in_and_Out_A4_t', ... 
{'cut_out','cut_in','out_host_lane','in_host_lane','undefined'}, ... 
[4;3;2;1;0],...
'Description', 'enum for signal Cut_in_and_Out_A4', ...
'DefaultValue', 'cut_out', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'Cut_in_and_Out_A4_t'];


Simulink.defineIntEnumType('BlinkerInfo_A4_t', ... 
{'both','right','left','off','unavailable'}, ... 
[4;3;2;1;0],...
'Description', 'enum for signal BlinkerInfo_A4', ...
'DefaultValue', 'both', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'BlinkerInfo_A4_t'];


Simulink.defineIntEnumType('ObstacleType_A4_t', ... 
{'Bicycle','pedestrian','bike','truck','vehicle'}, ... 
[4;3;2;1;0],...
'Description', 'enum for signal ObstacleType_A4', ...
'DefaultValue', 'Bicycle', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'ObstacleType_A4_t'];


Simulink.defineIntEnumType('Cut_in_and_Out_A3_t', ... 
{'cut_out','cut_in','out_host_lane','in_host_lane','undefined'}, ... 
[4;3;2;1;0],...
'Description', 'enum for signal Cut_in_and_Out_A3', ...
'DefaultValue', 'cut_out', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'Cut_in_and_Out_A3_t'];


Simulink.defineIntEnumType('BlinkerInfo_A3_t', ... 
{'both','right','left','off','unavailable'}, ... 
[4;3;2;1;0],...
'Description', 'enum for signal BlinkerInfo_A3', ...
'DefaultValue', 'both', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'BlinkerInfo_A3_t'];


Simulink.defineIntEnumType('ObstacleType_A3_t', ... 
{'Bicycle','pedestrian','bike','truck','vehicle'}, ... 
[4;3;2;1;0],...
'Description', 'enum for signal ObstacleType_A3', ...
'DefaultValue', 'Bicycle', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'ObstacleType_A3_t'];


Simulink.defineIntEnumType('ST_OBJ_DIST_HLB_t', ... 
{'invalid','oncoming','preceding','no'}, ... 
[3;2;vehicle;1],...
'Description', 'enum for signal ST_OBJ_DIST_HLB', ...
'DefaultValue', 'invalid', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'ST_OBJ_DIST_HLB_t'];


Simulink.defineIntEnumType('HeadwayValid_t', ... 
{'valid','not'}, ... 
[1;0],...
'Description', 'enum for signal HeadwayValid', ...
'DefaultValue', 'valid', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'HeadwayValid_t'];


Simulink.defineIntEnumType('CIPVFlag_t', ... 
{'CIPV','not'}, ... 
[1;0],...
'Description', 'enum for signal CIPVFlag', ...
'DefaultValue', 'CIPV', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'CIPVFlag_t'];


Simulink.defineIntEnumType('CIPVFlag_t', ... 
{'CIPV','not'}, ... 
[1;0],...
'Description', 'enum for signal CIPVFlag', ...
'DefaultValue', 'CIPV', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'CIPVFlag_t'];


Simulink.defineIntEnumType('CIPVFlag_t', ... 
{'CIPV','not'}, ... 
[1;0],...
'Description', 'enum for signal CIPVFlag', ...
'DefaultValue', 'CIPV', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'CIPVFlag_t'];


Simulink.defineIntEnumType('Cut_in_and_Out_A2_t', ... 
{'cut_out','cut_in','out_host_lane','in_host_lane','undefined'}, ... 
[4;3;2;1;0],...
'Description', 'enum for signal Cut_in_and_Out_A2', ...
'DefaultValue', 'cut_out', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'Cut_in_and_Out_A2_t'];


Simulink.defineIntEnumType('BlinkerInfo_A2_t', ... 
{'both','right','left','off','unavailable'}, ... 
[4;3;2;1;0],...
'Description', 'enum for signal BlinkerInfo_A2', ...
'DefaultValue', 'both', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'BlinkerInfo_A2_t'];


Simulink.defineIntEnumType('ObstacleType_A2_t', ... 
{'Bicycle','pedestrian','bike','truck','vehicle'}, ... 
[4;3;2;1;0],...
'Description', 'enum for signal ObstacleType_A2', ...
'DefaultValue', 'Bicycle', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'ObstacleType_A2_t'];


Simulink.defineIntEnumType('Cut_in_and_Out_A1_t', ... 
{'cut_out','cut_in','out_host_lane','in_host_lane','undefined'}, ... 
[4;3;2;1;0],...
'Description', 'enum for signal Cut_in_and_Out_A1', ...
'DefaultValue', 'cut_out', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'Cut_in_and_Out_A1_t'];


Simulink.defineIntEnumType('BlinkerInfo_A1_t', ... 
{'both','right','left','off','unavailable'}, ... 
[4;3;2;1;0],...
'Description', 'enum for signal BlinkerInfo_A1', ...
'DefaultValue', 'both', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'BlinkerInfo_A1_t'];


Simulink.defineIntEnumType('ObstacleType_A1_t', ... 
{'Bicycle','pedestrian','bike','truck','vehicle'}, ... 
[4;3;2;1;0],...
'Description', 'enum for signal ObstacleType_A1', ...
'DefaultValue', 'Bicycle', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'ObstacleType_A1_t'];


Simulink.defineIntEnumType('Cut_in_and_Out_A0_t', ... 
{'cut_out','cut_in','out_host_lane','in_host_lane','undefined'}, ... 
[4;3;2;1;0],...
'Description', 'enum for signal Cut_in_and_Out_A0', ...
'DefaultValue', 'cut_out', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'Cut_in_and_Out_A0_t'];


Simulink.defineIntEnumType('BlinkerInfo_A0_t', ... 
{'both','right','left','off','unavailable'}, ... 
[4;3;2;1;0],...
'Description', 'enum for signal BlinkerInfo_A0', ...
'DefaultValue', 'both', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'BlinkerInfo_A0_t'];


Simulink.defineIntEnumType('ObstacleType_A0_t', ... 
{'Bicycle','pedestrian','bike','truck','vehicle'}, ... 
[4;3;2;1;0],...
'Description', 'enum for signal ObstacleType_A0', ...
'DefaultValue', 'Bicycle', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'ObstacleType_A0_t'];


Simulink.defineIntEnumType('Close_Car_t', ... 
{'Close','No'}, ... 
[1;car],...
'Description', 'enum for signal Close_Car', ...
'DefaultValue', 'Close', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'Close_Car_t'];


end
